spring.datasource.url=jdbc:postgresql://PROD_HOST:5432/online_platform
spring.datasource.username=PROD_USER
spring.datasource.password=PROD_PASSWORD
spring.datasource.driver-class-name=org.postgresql.Driver
