spring.application.name=platform-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/online_platform
spring.datasource.username=platform
spring.datasource.password=platform
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migrationserver.port=${PORT:8080}
